# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('jan_data', models.IntegerField()),
                ('feb_data', models.IntegerField()),
                ('mar_data', models.IntegerField()),
                ('apr_data', models.IntegerField()),
                ('may_data', models.IntegerField()),
                ('jun_data', models.IntegerField()),
                ('jul_data', models.IntegerField()),
                ('aug_data', models.IntegerField()),
                ('sep_data', models.IntegerField()),
                ('oct_data', models.IntegerField()),
                ('nov_data', models.IntegerField()),
                ('dec_data', models.IntegerField()),
                ('yaxis_val', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pdfdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
    ]
