# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WASapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdata',
            name='pdffile',
            field=models.FileField(null='true', upload_to='uploads/'),
        ),
    ]
