# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WASapp', '0002_pdfdata_pdffile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdata',
            name='pdffile',
            field=models.FileField(null='true', upload_to='WASapp/uploads/'),
        ),
    ]
